---
components:
- name: jenkins-iam-role
  source:
    repoUrl: https://github.com/agilestacks/components.git
    repoPath: components/jenkins-iam-role
    dir: components/jenkins-iam-role
    branch: master
    fromEnv: GITHUB_TOKEN

lifecycle:
  order:
    - jenkins-iam-role

parameters:
- name: dns.domain
- name: cloud.region
- name: cloud.role.worker
