---
version: 1
kind: application
meta:
  name: argo-workflows:1
  brief: >
    Argo worfklow application with minio bucket trigger and a GitHub
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: master
    fromEnv: GITHUB_TOKEN

components: []

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]

parameters: []
templates:
  files:
    - "*.template"

outputs:
- name: application.git.remote
  value: ${component.git.remote}
- name: application.webhook.url
  value: ${component.argo.ingress}/webhooks/${application.name}/${application.webhook}
- name: application.webhook.method
  value: POST
