---
version: 1
kind: application
meta:
  name: argo-workflows:1
  brief: >
    Argo worfklow application with minio bucket trigger and a GitHub
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: master
    fromEnv: GITHUB_TOKEN

components: []

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]

parameters:
- name: application
  parameters:
  - name: name
  - name: webhook.name
    value: run
  - name: webhook.method
    value: POST
  - name: namespace
    value: argoproj
    env: NAMESPACE
- name: component.argo
  parameters:
  - name: namespace
  - name: ingress
  - name: events.webhook.service.name
  - name: events.webhook.service.port
- name: component.ingress
  parameters:
  - name: protocol
  - name: urlPrefix
  - name: fqdn
- name: component.buildbox
  parameters:
  - name: directory
    value: .
  - name: dockerfile
    value: Dockerfile


templates:
  files:
    - "*.template"

outputs:
- name: application.git.remote
  value: ${component.git.remote}
- name: application.webhook.url
  value: ${component.argo.ingress}/webhooks/${application.name}/${application.webhook}
- name: application.webhook.method
  value: POST
