---
version: 1
kind: application
meta:
  name: argo-workflows:1
  brief: >
    Argo worfklow application with minio bucket trigger and a GitHub
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates/argo-workflows
    dir: .
    branch: master
    fromEnv: GITHUB_TOKEN

components: []

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]

parameters: []
templates:
  files:
    - "*.template"
