---
components:
- name: ecr
  source:
    repository: https://github.com/agilestacks/components.git
    repoDir: components/ecr
    branch: master
    fromEnv: GITHUB_TOKEN

lifecycle:
  order:
    - ecr
  mandatory:
    - ecr

parameters:
- name: dns.domain
- name: cloud.region
- name: terraform.bucket
  parameters:
  - name: name
  - name: region
- name: component.ecr.name
  value: myargoapp.${dns.domain}
