---
components:
- name: github-repository
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components
    dir: components/github-repository
    branch: master
    fromEnv: GITHUB_TOKEN
- name: buildbox
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components
    dir: components/buildbox
    branch: master
    fromEnv: GITHUB_TOKEN
# - name: github-webhook
#   source:
#     repoUrl: https://github.com/agilestacks/applications.git
#     repoPath: applications/components
#     dir: components/github-webhook
#     branch: master
#     fromEnv: GITHUB_TOKEN

lifecycle:
  order:
    - github-repository
    - buildbox
    # - github-webhook
  mandatory:
    - github-repository
    - buildbox
    # - github-webhook

parameters:
- name: component.git
  parameters:
  - name: remote
- name: component.github
  parameters:
  - name: token
    fromEnv: COMPONENT_GITHUB_TOKEN
  - name: repository.organization
    value: asibot
  - name: repository.name
    value: antonargo1
  - name: webhook.name
    value: github
  - name: webhook.events.json
    value: '["push"]'
  - name: repository.description
    value: >
      Worfklow application template backed with Argo.
      Optimized to carry simulation and data science tasks

outputs:
- name: application.git.remote
  value: ${component.git.remote}
