---
components:
- name: github-repository
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/github-repository
    dir: components/github-repository
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN
- name: buildbox
  source:
    repoUrl: https://github.com/agilestacks/buildbox.git
    repoPath: buildbox
    dir: components/buildbox
    branch: COMPONENTS_TAG
    fromEnv: GITHUB_TOKEN

lifecycle:
  order:
    - github-repository
    - buildbox

parameters:
- name: component.git
  parameters:
  - name: remote
  - name: user.name
    value: Super Hub
  - name: user.email
    value: support@agilestacks.com

- name: component.github
  parameters:
  - name: token
    fromEnv: COMPONENT_GITHUB_TOKEN
  - name: repository.organization
    value: asibot
  - name: repository.name
    value: antonargo1
  - name: webhook.name
    value: github
  - name: webhook.events.json
    value: '["push"]'
  - name: repository.description
    value: >
      Worfklow application template backed with Argo.
      Optimized to carry simulation and data science tasks

outputs:
- name: application.git.kind
  value: github
- name: application.git.remote
  value: ${component.git.remote}
