---
components:
- name: minio-source
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components
    dir: components/minio-bucket
    branch: master
    fromEnv: GITHUB_TOKEN
- name: minio-target
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components
    dir: components/minio-bucket
    branch: master
    fromEnv: GITHUB_TOKEN

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]
  order:
    - minio-bucket
  mandatory:
    - minio-bucket

parameters:
- name: cloud.region
- name: terraform.bucket
  parameters:
  - name: name
  - name: region
- name: component.ingress
  parameters:
  - name: protocol
- name: component.bucket
  component: minio-source
  parameters:
  - name: endpoint
  - name: name
    value: myapplication
  - name: namespace
  - name: secret.name
  - name: secret.namespace
  - name: secret.accessKeyRef
  - name: secret.secretKeyRef
- name: component.bucket
  component: minio-target
  parameters:
  - name: endpoint
  - name: name
    value: myapplication
  - name: namespace
  - name: secret.name
  - name: secret.namespace
  - name: secret.accessKeyRef
  - name: secret.secretKeyRef
- name: component.nats.fqdn
# - name: component.minio
#   parameters:
#   - name: service.host
#   - name: service.port
