---
components:
- name: source-bucket
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/minio-bucket
    dir: components/minio-bucket
    branch: COMPONENTS_TAG
    fromEnv: GITHUB_TOKEN
- name: target-bucket
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/minio-bucket
    dir: components/minio-bucket
    branch: COMPONENTS_TAG
    fromEnv: GITHUB_TOKEN

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]
  order:
    - source-bucket
    - target-bucket

parameters:
- name: cloud.region
- name: component.nats.fqdn

- name: terraform.bucket
  parameters:
  - name: name
  - name: region

- name: component.ingress
  parameters:
  - name: protocol

- name: component.bucket
  parameters:
  - name: endpoint
  - name: secret.name
  - name: secret.accessKeyRef
  - name: secret.secretKeyRef

- name: component.bucket
  component: source-bucket
  parameters:
  - name: name
    value: ${application.name}-input
  - name: event.prefix
    value: ""

- name: component.bucket
  component: target-bucket
  parameters:
  - name: name
    value: ${application.name}-output
  - name: event.prefix
    value: ""

- name: application.source.bucket
  kind: link
  parameters:
  - name: name
    value: ${source-bucket:component.bucket.name}
  - name: endpoint
    value: ${component.bucket.endpoint}
    env: DEST_BUCKET_ENDPOINT
  - name: secret.name
    value: ${component.bucket.secret.name}
    env: DEST_BUCKET_SECRET_NAME
  - name: secret.accessKeyRef
    value: ${component.bucket.secret.accessKeyRef}
    env: DEST_BUCKET_ACCESSKEY
  - name: secret.secretKeyRef
    value: ${component.bucket.secret.secretKeyRef}
    env: DEST_BUCKET_SECRETKEY
  - name: prefix
    value: ${source-bucket:component.bucket.event.prefix}
    empty: allow
    kind: user
  - name: suffix
    value: ""
    empty: allow
    kind: user

- name: application.target.bucket
  kind: link
  parameters:
  - name: name
    value: ${target-bucket:component.bucket.name}
  - name: endpoint
    value: ${component.bucket.endpoint}
    env: SRC_BUCKET_ENDPOINT
  - name: secret.name
    value: ${component.bucket.secret.name}
    env: SRC_BUCKET_SECRET_NAME
  - name: secret.accessKeyRef
    value: ${component.bucket.secret.accessKeyRef}
    env: SRC_BUCKET_ACCESSKEY
  - name: secret.secretKeyRef
    value: ${component.bucket.secret.secretKeyRef}
    env: SRC_BUCKET_SECRETKEY
  - name: prefix
    value: ${source-bucket:component.bucket.event.prefix}
    empty: allow
    kind: user
  - name: suffix
    value: ""
    empty: allow
    kind: user
