apiVersion: skaffold/v1
build:
  artifacts:
  - image: detective
    sync:
      manual:
      - dest: /app
        src: src/**/*.py
        strip: src/
      - dest: /app
        src: src/static/**
        strip: src/
  tagPolicy:
    dateTime:
      format: 20060102-150405
deploy:
  kubectl:
    manifests:
    - k8s/*
kind: Config
metadata:
  name: detective-
profiles:
- activation:
  - env: KUBECONFIG=!
  build:
    local:
      useDockerCLI: true
  name: local
- build:
    cluster:
      dockerConfig:
        path: .dockerconfig.json
  name: incluster
