---
version: 1
kind: application
meta:
  name: java-application:1
  brief: Java Application
  source:
    dir: ./

requires:
  - kubernetes

components:
- name: application-ecr
  source:
    dir: ../components/ecr

lifecycle:
  verbs: [deploy, undeploy]
  order:
    - application-ecr
  mandatory:
    - application-ecr

parameters:
  - name: component.java-application
    parameters:
      - name: name
        value: java-application
        env: NAME
      - name: namespace
        value: application
        env: NAMESPACE
      - name: uri
        value: java-application
  - name: terraform.bucket.name
    env: STATE_BUCKET
  - name: terraform.bucket.region
    env: STATE_REGION
  - name: component.ingress.fqdn
  - name: dns.domain
    env: DOMAIN_NAME
  - name: component.ecr
    component: application-ecr
    parameters:
      - name: name
        value: agilestacks/${dns.domain}/${component.java-application.name}
  - name: component.ecr.image
    env: IMAGE

outputs:
  - name: component.java-application.ui
    brief: Web UI address
    value: http://${component.java-application.uri}.${component.ingress.fqdn}
  - name: component.java-application.ecr
    component: application-ecr
    brief: Docker image
    fromTfVar: image_name

templates:
  files:
    - "*.template"
