.DEFAULT_GOAL := install

install:
	@echo "Error: Can't initialize application workspace. No git repository. Try update or force delete"
	@exit 1
.PHONY: install

uninstall:
	@echo "Error: Can't initialize application workspace"
	@echo "Error: Git repo #repo_url# has not been found (Deleted already?)"
	@echo "Try force delete"
	@exit 1
.PHONY: uninstall
