---
apiVersion: v1
kind: Secret
type: goofysflex
metadata:
  name: minio-creds
data:
  accesskey: YWRtaW4=
  secretkey: QWRtaW4xMjM0NQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data2
          mountPath: /data2
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "sleep infinity" ]
      volumes:
      - name: data2
        flexVolume:
          driver: "goofysflex"
          secretRef:
            name: minio-creds
          options:
            # Required
            bucket: "default"
            endpoint: "https://cluster-red-minio.app.cluster-red.antoncloud1.superhub.io"
      # - name: data
      #   nfs:
      #     # URL for the NFS server
      #     server: 10.3.171.111 # Change this!
      #     path: /
      # - name: data
      #   persistentVolumeClaim:
      #    claimName: nfs-bucket
