---
version: 1
kind: application
meta:
  name: 'jupyter-notebook:1'
  brief: Jupyter notebook application
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: master
    fromEnv: GITHUB_TOKEN
requires:
  - kubernetes
components: []
parameters:
  - name: component.ingress.protocol
  - name: application.name
    value: viktors-notebook
    env: NAME
  - name: application.description
    value: Java application
  - name: application.state.file
    fromEnv: APP_STATE_FILE
  - name: application.image
  - name: component.jupyterhub.url
  - name: application.notebook.token
    fromTfVar: token           
outputs:
  - name: application.url 
    value: '${component.jupyterhub.url}/user/${application.name}/?token=${application.notebook.token}'
