---
version: 1
kind: application
meta:
  name: 'jupyter-notebook:1'
  brief: Jupyter notebook application
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN

requires:
  - jupyterhub

components: []

parameters:
  - name: dns.domain
    env: DOMAIN_NAME
  - name: component.ingress.protocol
  - name: application.name
    value: viktors-notebook
  - name: application.name.internal
    value: ${application.name}
    env: APPLICATION
  - name: application.description
    value: Java application
  - name: application.state.file
    fromEnv: APP_STATE_FILE
  - name: application.image
  - name: component.jupyterhub.url

outputs:
  - name: application.notebook.token
    fromTfVar: token
  - name: application.url
    value: '${component.jupyterhub.url}/user/${application.name}/?token=${application.notebook.token}'
