---
components:
- name: github-repository
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/github-repository
    dir: components/github-repository
    branch: COMPONENTS_TAG
    fromEnv: GITHUB_TOKEN
- name: buildbox
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/buildbox
    dir: components/buildbox
    branch: COMPONENTS_TAG
    fromEnv: GITHUB_TOKEN

lifecycle:
  order:
    - github-repository
    - buildbox

parameters:
- name: component.buildbox.docker.image
- name: component.buildbox.docker.tag
- name: component.git
  parameters:
  - name: remote
- name: component.github
  parameters:
  - name: token
    fromEnv: COMPONENT_GITHUB_TOKEN
    default: token
  - name: repository.organization
    value: asibot
  - name: repository.name
    value: antonargo1
  - name: webhook.name
    value: github
  - name: webhook.events.json
    value: '["push"]'
  - name: repository.description
    value: >
      Jupyter Notebook Sample Application

outputs:
- name: application.git.remote
  value: ${component.git.remote}
- name: application.git.token
  value: ${component.github.token}
