---
version: 1
kind: application
meta:
  name: 'spring-boot:1'
  brief: Java microservice with Spring Boot
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: master
    fromEnv: GITHUB_TOKEN
requires:
  - kubernetes
components: []
parameters:
  - name: application.name
    value: viktors-93
  - name: application.description
    value: Java application
  - name: application.namespace
    value: cool
  - name: application.replicas
    value: 1
  - name: application.version
    value: latest
  - name: application.state.file
    fromEnv: APP_STATE_FILE
  - name: application.ingress.host
    value: '${application.name}.${component.ingress.fqdn}'
  - name: application.path
    value: /
  - name: component.ingress.fqdn
  - name: component.docker.image
  - name: component.git.remote
  - name: component.jenkins.fqdn                
outputs:
  - name: application.git.remote
    value: '${component.git.remote}' 
  - name: application.docker.image
    value: '${component.docker.image}' 
  - name: application.name
    value: '${application.name}'
  - name: application.namespace
    value: '${application.namespace}'  
  - name: application.fqdn
    value: '${application.ingress.host}'
  - name: application.path
    value: '${application.path}' 
  - name: application.jenkins.pipeline.url
    value: '${component.jenkins.url}/job/${application.name}-pipeline'     
templates:
  files:
    - templates/*.template
