apiVersion: "machinelearning.seldon.io/v1alpha2"
kind: "SeldonDeployment"
metadata:
  name: "anton-agilestacks-com"
  namespace: "kubeflow"
  labels:
    app: "seldon"
spec:
  annotations:
    deployment_version: "v1"
    project_name: "anton-agilestacks-com"
  name: "anton-agilestacks-com"
  predictors:
  - annotations:
      predictor_version: "v1"
    componentSpecs:
    - spec:
        containers:
        - name: "anton-agilestacks-com"
          image: "kubeflow-harbor.svc.cluster-red.antoncloud.superhub.io/library/seldon:5"
          imagePullPolicy: "Always"
          env:
          - name: MODEL_FILE
            value: "/mnt/s3/training/training1.h5"
          - name: TITLE_PP_FILE
            value: "/mnt/s3/training/title_preprocessor.dpkl"
          - name: BODY_PP_FILE
            value: "/mnt/s3/training/body_preprocessor.dpkl"
          volumeMounts:
          - mountPath: ""
            name: "persistent-storage"
        terminationGracePeriodSeconds: 1
        volumes:
        - name: "persistent-storage"
          volumeSource:
            persistentVolumeClaim:
              claimName: "anton-agilestacks-com-bucket"
    graph:
      children: []
      endpoint:
        type: "REST"
      name: "anton-agilestacks-com"
      type: "MODEL"
    name: "anton-agilestacks-com"
    replicas: 1
