apiVersion: "machinelearning.seldon.io/v1alpha2"
kind: "SeldonDeployment"
metadata:
  name: "{{NAME}}"
  namespace: "{{NAMESPACE}}"
  labels:
    app: "seldon"
spec:
  annotations:
    deployment_version: "{{VERSION}}"
    project_name: "{{NAME}}"
    seldon.io/ambassador-config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: "serving-{{NAME}}"
      prefix: serving/models/{{NAME}}/
      rewrite: /v1/models/{{NAME}}:predict
      method: POST
      service: "{{NAME}}.{{NAMESPACE}}:5000"
  name: "{{NAME}}"
  predictors:
  - annotations:
      predictor_version: "{{VERSION}}"
    componentSpecs:
    - spec:
        containers:
        - name: "{{NAME}}"
          image: "{{SERVING_IMAGE}}"
          imagePullPolicy: "Always"
          env:
          - name: MODEL_FILE
            value: "{{MODEL_FILE}}"
          - name: TITLE_PP_FILE
            value: "{{TITLE_PP_FILE}}"
          - name: BODY_PP_FILE
            value: "{{BODY_PP_FILE}}"
          volumeMounts:
          - mountPath: "{{MOUNT_POINT}}"
            name: "persistent-storage"
        terminationGracePeriodSeconds: 1
        volumes:
        - name: "persistent-storage"
          volumeSource:
            persistentVolumeClaim:
              claimName: "{{PVC_NAME}}"
    graph:
      children: []
      endpoint:
        type: "REST"
      name: "{{NAME}}"
      type: "MODEL"
    name: "{{NAME}}"
    replicas: {{REPLICAS}}
