apiVersion: v1
kind: Pod
metadata:
  generateName: kaniko-
  namespace: default
spec:
  restartPolicy: Never
  serviceAccountName: default
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v0.5.0
    args: ["--cache=true",
                "--dockerfile=dockerfile",
                "--context=gs://mlpipeline/kaniko_build.tar.gz",
                "--destination={{IMAGE}}:latest"]
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/gcp-credentials/user-gcp-sa.json
    volumeMounts:
    - mountPath: /secret/gcp-credentials
      name: gcp-credentials
  volumes:
  - name: gcp-credentials
    secret:
      secretName: user-gcp-sa
