#!/usr/bin/env groovy

@Library('agilestacks') _

properties([
        pipelineTriggers([
                [$class: 'GitHubPushTrigger'],
                pollSCM('H/1 * * * *')
        ])
])

node('master') {
    stage('Checkout') {
        checkout scm
    }
}

def uuid = UUID.randomUUID().toString()

podTemplate(
        inheritFrom: 'toolbox',
        label: uuid,
        containers: [
                containerTemplate(
                        name: 'java',
                        image: 'openjdk:jdk',
                        ttyEnabled: true,
                        command: 'cat'
                )],
        volumes: [
                emptyDirVolume(memory: false, mountPath: '/root/.gradle')
        ]
) {
    node(uuid) {
        def gradleProps
        container('java') {
            stage("Compile") {
                gradleProps = sh(script: './gradlew properties -q', returnStdout: true)
                    .split('\n')
                    .collect { it.tokenize(':') }
                    .findAll { it.size() > 1 }
                    .collectEntries { [(it[0].trim()):it[1].trim()] }

                sh script: './gradlew clean build allureReport'
                archiveArtifacts "build/libs/*.jar"
                junit 'build/test-results/test/*.xml'
                publishHTML([
                        reportDir: 'build/reports/allure-report',
                        reportFiles: 'index.html',
                        reportName: 'Allure Report',
                        keepAll: true
                ])
            }
        }

        container('toolbox') {
            def dockerImage

            environment {
                NAME: params.NAME
            }
            stage('Prepare dependencies') {
                withAWS(role:env.DEPLOY_ROLE_ARN) {
                    hub.elaborate(state: params.STATE_FILE)
                    hub.deploy()
                    dockerImage = hub.explain().stackOutputs['application.image'] as String
                }
            }

            def commit = commitHash.shortHash()
            def images = [ "$dockerImage:$commit", "$dockerImage:latest" ]

            stage('Build') {
                sh script: """
                    docker build --pull \
                         --rm \
                         --build-arg APP_NAME=${gradleProps['archivesBaseName']} \
                         --build-arg APP_VERSION=${gradleProps['version']} \
                         ${images.collect{"--tag $it"}.join(' ')} .
                """
            }
            stage('Push') {
                ecr.login()
                def pushImages = images.collectEntries{ [it: { sh script: "docker push $it" }]}

                parallel pushImages
            }

            def template = readFile 'deployment.yaml'
            def deployment = render.template template, [
                    app:            params.NAME,
                    namespace:      params.NAMESPACE,
                    replicas:       params.REPLICAS,
                    host:           params.INGRESS_HOST,
                    image:          "$dockerImage:$commit",
                    version:        gradleProps['version']
            ]
            stage('Deploy') {
                writeFile file: "deployment-build-${currentBuild.number}.yaml", text: deployment
                def exists = sh returnStatus: true, script: "kubectl -n ${params.NAMESPACE} get -f deployment-build-${currentBuild.number}.yaml"
                try {
                    if (exists == 0) {
                        sh script: "kubectl -n ${params.NAMESPACE} set image --record deployment/${params.NAME} '${params.NAME}=${dockerImage}:$commit'"
                    } else {
                        sh script: "kubectl -n ${params.NAMESPACE} apply --force --record -f deployment-build-${currentBuild.number}.yaml"
                    }
                    sh script: "kubectl -n ${params.NAMESPACE} rollout status -w 'deployment/${params.NAME}'"
                } catch(err) {
                    sh script: """
            kubectl -n ${params.NAMESPACE} rollout undo 'deployment/${params.NAME}'
            kubectl -n ${params.NAMESPACE} rollout status -w 'deployment/${params.NAME}'
          """

                    error message: """
            Failed to deploy ${params.NAME} with container $dockerImage:$commit \n
            We rolled back unsuccessful deployment
          """
                }
            }
        }
        stage('Validate') {
            retry(20) {
                sleep 1
                def resp = httpRequest url: "http://${params.INGRESS_HOST}/status"
                echo resp.content
                assert resp.status == 200
            }
        }
    }
}
