---
version: 1
kind: application
meta:
  name: argo-app:1
  brief: >
    Argo worfklow application with s3 trigger
  source:
    dir: .

components:
- name: ecr
  source:
    dir: ../../../components/ecr
- name: github
  source:
    dir: ../../components/github
- name: bucket
  source:
    dir: ../../components/minio-bucket
- name: bucket-sensor
  source:
    dir: ../../components/argo-sensor-artifact

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]
  order:
    - ecr
    - github
    - bucket
    - bucket-sensor
  mandatory:
    - ecr
    - github
    - bucket
    - bucket-sensor

parameters:
- name: dns.domain
- name: cloud.region
- name: terraform.bucket.name
  # fromEnv: STATE_BUCKET
- name: terraform.bucket.region
- name: component.ingress.protocol


- name: component.minio.service.host
- name: component.minio.service.port
# - name: component.minio
#   parameters:
#   - name: endpoint
#   - name: endpoint.ingress
#   - name: namespace
#   - name: secret.name
#   - name: secret.accessKeyRef
#   - name: secret.secretKeyRef

- name: component.bucket
  parameters:
  - name: endpoint
  - name: name
    value: myapplication
  - name: namespace
  - name: secret.name
  - name: secret.namespace
  - name: secret.accessKeyRef
  - name: secret.secretKeyRef

- name: component.bucket.endpoint
  component: bucket-sensor
  value: ${component.minio.service.host}:${component.minio.service.port}

- name: component.argo.namespace
- name: component.argo.sensor.subject
  value: ${component.bucket.name}-events
- name: component.nats.fqdn

- name: component.github
  parameters:
  - name: token
    fromEnv: GITHUB_TOKEN
  - name: repository.organization
    value: asibot
  - name: repository.name
    value: antonargo1
  - name: repository.description
    value: >
      Worfklow application template backed with Argo.
      Optimized to carry simulation and data science tasks
- name: component.ecr.name
  value: myargoapp.${dns.domain}

templates:
  files:
    - "*.template"
