---
version: 1
kind: application
meta:
  name: argo-app:1
  brief: >
    Argo worfklow application with s3 trigger
  source:
    dir: .

components:
- name: ecr
  source:
    dir: ../../../components/ecr
- name: github
  source:
    dir: ../../components/github
- name: bucket
  source:
    dir: ../../components/minio-bucket

lifecycle:
  bare: allow
  verbs: [deploy, undeploy]
  order:
    - ecr
    - github
    - bucket
  mandatory:
    - ecr
    - github
    - bucket

parameters:
- name: dns.domain
- name: cloud.region
- name: terraform.bucket.name
  # fromEnv: STATE_BUCKET
- name: terraform.bucket.region
- name: component.ingress.protocol

- name: component.minio
  parameters:
  - name: endpoint
  - name: endpoint.ingress
  - name: namespace
  - name: secret.name
  - name: secret.accessKeyRef
  - name: secret.secretKeyRef

- name: component.bucket
  component: bucket
  parameters:
  - name: endpoint
    value: ${component.minio.endpoint.ingress}
  - name: name
    value: myapplication
  - name: namespace
  - name: secret.name
  - name: secret.namespace
  - name: secret.accessKeyRef
  - name: secret.secretKeyRef


- name: component.argo.repo
  parameters:
  - name: secret.name
  - name: secret.accessKeyRef
  - name: secret.secretKeyRef
  - name: bucket.name
  - name: bucket.region
  - name: bucket.endpoint
  - name: iam.username
  - name: minio.bucket.name
  # fromEnv: STATE_REGION

- name: component.github
  parameters:
  - name: token
    fromEnv: GITHUB_TOKEN
  - name: repository.organization
    value: asibot
  - name: repository.name
    value: antonargo1
  - name: repository.description
    value: >
      Worfklow application template backed with Argo.
      Optimized to carry simulation and data science tasks
- name: component.ecr.name
  value: myargoapp.${dns.domain}

templates:
  files:
    - "*.template"
