apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: arguments-via-webhook-event
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello world
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["Hello, world!"]
