---
components:
- name: git-branch
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/git-branch
    dir: components/git-branch
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN
lifecycle:
  order:
    - git-branch


parameters:
- name: application.git.kind
- name: component.git.token
- name: component.git.organization
- name: component.git.remote
- name: component.gitBranch
  parameters:
  - name: git.token
    value: ${component.git.token}
    env: GIT_TOKEN
  - name: git.branch
    value: ${promotion.branch}
    env: BRANCH_NAME 
  - name: git.repository
    value: ${application.git.remote}
    env: REMOTE
  - name: git.organization
    value: ${component.git.organization}
    env: ORGANIZATION
  - name: git.kind
    value: ${application.git.kind}
    env: GIT_KIND     

outputs:
- name: application.git.branch
  value: ${component.gitOrphan.git.branch}
- name: promotion.git.remote
  value: ${component.gitOrphan.url}
          