---
components:
- name: github-orphan
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/github-orphan
    dir: components/github-orphan
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN
lifecycle:
  order:
    - github-orphan
parameters:
- name: component.githubOrphan
  parameters:
  - name: git.token
    fromEnv: COMPONENT_GITHUB_TOKEN
  - name: git.branch
    value: ${promotion.branch}   
  - name: git.repository
    value: ${application.git.remote}
  - name: url
outputs:
- name: application.git.branch
  value: ${component.githubOrphan.git.branch}
- name: promotion.git.remote
  value: ${component.githubOrphan.url}
          