---
components:
- name: xaccount-role
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/xaccount-role
    dir: components/xaccount-role
    branch: master
    fromEnv: GITHUB_TOKEN
lifecycle:
  order:
    - xaccount-role
parameters:
- name: component.xaccountRole
  parameters: 
  - name: target.awsAccessKey
    fromEnv: TARGET_AWS_ACCESS_KEY_ID
  - name: target.awsSecretKey
    fromEnv: TARGET_AWS_SECRET_ACCESS_KEY
  - name: target.awsSessionKey
    fromEnv: TARGET_AWS_SESSION_TOKEN
  - name: roleArn  
  - name: name
    value: ${application.target.environment}.${application.name}
outputs:  
- name: application.target.roleArn  
  value: ${component.xaccountRole.roleArn}
                