---
version: 1
kind: application
meta:
  name: 'react-es2018:1'
  brief: S3 hosted React frontend application
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN

requires:
  - kubernetes

components: []

parameters:
  - name: application
    parameters:
    - name: name
      value: react-app-next
    - name: description
      value: React application
    - name: version
      value: latest
    - name: state.file
      fromEnv: APP_STATE_FILE
    - name: protocol
      value: http
    - name: ingress
      value: '${component.s3website.name}.${dns.domain}'
    - name: theme
    - name: pipeline.name
      value: main
  - name: component.git.remote
  - name: component.jenkins.url
  - name: component.s3website.name
    value: ${application.name}
  - name: component.s3website.path
  - name: dns.domain
    env: DOMAIN_NAME
  - name: cloud.region
  - name: terraform.bucket
    parameters:
    - name: name
    - name: region

outputs:
  - name: application.git.remote
    value: '${component.git.remote}'
  - name: application.name
    value: '${application.name}'
  - name: application.theme
  - name: application.path
    value: '${component.s3website.path}'
  - name: application.url
    value: '${application.protocol}://${application.ingress}/${application.path}'
  - name: application.bucket
    value: '${component.s3website.bucket}'
  - name: application.jenkins.pipeline.url
    value: '${component.jenkins.url}/job/${application.name}/job/${application.pipeline.name}-${application.name}'

templates:
  files:
    - templates/*.template
