---
version: 1
kind: application
meta:
  name: 'kubeflow-pipeline:1'
  brief: 'Kubeflow Pipeline end-to-end applicaiton'
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/app-templates
    dir: .
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN
requires:
  - kubernetes

parameters:
- name: dns.domain
  env: KUBECONTEXT
- name: cloud.region
- name: terraform.bucket.name
- name: terraform.bucket.region
- name: application
  parameters:
  - name: name
    env: APPLICATION
  - name: description
    value: End-to-end Kubeflow pipeline
  - name: workspace.dir
    default: ../../../
    fromEnv: WORKSPACE
  - name: workspace.size
    value: 10Gi
  - name: workspace.uid
    brief: stands for jovyan user
    value: '1000'
  - name: workspace.gid
    brief: stands for jovyan  user primary group
    value: '100'
  - name: namespace
    kind: user
    value: kubeflow
    # kind: link
    # value: ${component.kubeflow.namespace}
    env: NAMESPACE

- name: component.kubeflow.url
- name: component.kubeflow.namespace

outputs:
- name: application.notebook.url
  value: "${component.kubeflow.url}_/notebooks"
  brief: URL to the application jupyter notebook

templates:
  files:
  - "templates/*.template"
