---
components:
- name: github-repository
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/github-repository
    dir: components/github-repository
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN

lifecycle:
  order:
    - github-repository

parameters:
- name: component.github
  parameters:
  - name: token
    fromEnv: COMPONENT_GITHUB_TOKEN
  - name: repository.organization
  - name: repository.name
  - name: repository.description
    kind: link
    value: ${application.description}
  - name: workspace
    kind: link
    value: ${application.workspace.dir}

- name: component.git
  parameters:
  - name: kind
    value: github
  - name: remote
  - name: username
  - name: password
  - name: branch
  - name: secretName
    kind: link
    value: ${application.name}-github
outputs:
- name: application.git.kind
  value: ${component.git.kind}
  brief: Reference that application uses Github
- name: application.git.remote
  value: ${component.git.remote}
  brief: URL to the git repository
- name: application.git.branch
  value: ${component.git.branch}
  brief: Git branch that current application stack is using
templates:
  files:
  - "templates/git-secret.yaml.template"
