---
components:
- name: pull-secret
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/pull-secret
    dir: components/pull-secret
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN

lifecycle:
  order:
    - pull-secret

parameters:
- name: application.jupyter.kernel.docker
  kind: user
  parameters:
  - name: registry.image
  - name: registry.url
  - name: auth.host
  - name: auth.basic.username
  - name: auth.basic.password
    fromEnv: APPLICATION_JUPYTER_KERNEL_DOCKER_AUTH_BASIC_PASSWORD
  - name: registry.kind

- name: component.pullSecret
  kind: link
  parameters:
  - name: name
    value: ${application.name}-pullsecret
  - name: namespace
    value: ${application.namespace}
- name: component.docker
  kind: link
  parameters:
  - name: registry.kind
    value: ${application.jupyter.kernel.docker.registry.kind}
  - name: auth.host
    value: ${application.jupyter.kernel.docker.auth.host}
  - name: auth.basic.username
    value: ${application.jupyter.kernel.docker.auth.basic.username}
  - name: auth.basic.password
    value: ${application.jupyter.kernel.docker.auth.basic.password}
