---
components:
- name: bucket
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/minio-bucket
    dir: components/bucket
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN
- name: s3fuse
  source:
    repoUrl: https://github.com/agilestacks/kubeflow-extensions.git
    repoPath: kubeflow-extensions/storage/s3fs
    dir: components/s3fs
    branch: master
    fromEnv: GITHUB_TOKEN
parameters:
- name: application.bucket
  kind: user
  parameters:
  - name: name
  - name: endpoint
  # not needed for minio
  # - name: region
  - name: accessKey
    fromEnv: APPLICATION_BUCKET_ACCESSKEY
  - name: secretKey
    fromEnv: APPLICATION_BUCKET_SECRETKEY
  - name: capacity
    value: 40Gi
- name: component.ingress.protocol
  value: https
- name: component.bucket
  kind: link
  parameters:
  - name: kind
    kind: user
    value: minio
  - name: name
    value: ${application.bucket.name}
  - name: endpoint
    value: ${application.bucket.endpoint}
  - name: accessKey
    value: ${application.bucket.accessKey}
  - name: secretKey
    value: ${application.bucket.secretKey}
- name: component.s3fuse.namespace
  kind: link
  value: ${application.namespace}

lifecycle:
  order:
  - s3fuse
  - bucket

outputs:
- name: application.bucket.url
  value: ${application.bucket.endpoint}/minio/${application.bucket.name}
  brief: URL of a bucket that has been used to store application artifacts
