---
components:
- name: aws-iam
  source:
    dir: components/aws-iam
- name: s3-bucket
  source:
    repoUrl: https://github.com/agilestacks/components.git
    repoPath: components/s3-bucket
    dir: components/s3-bucket
    branch: COMPONENTS_TAG
    fromEnv: GITHUB_TOKEN
- name: s3fuse
  source:
    repoUrl: https://github.com/agilestacks/kubeflow-extensions.git
    repoPath: kubeflow-extensions/storage/s3fs
    dir: components/s3fs
    branch: master
    fromEnv: GITHUB_TOKEN
parameters:
- name: application.bucket
  kind: user
  parameters:
  - name: name
  - name: region
  - name: pvc.capacity
    value: 600Gi
- name: component.ingress.protocol
  value: https
- name: component.s3
  kind: user
  parameters:
  - name: kind
    value: s3
  - name: name
    kind: link
    value: ${application.bucket.name}
  - name: acl
    value: private
- name: component.s3fuse.namespace
  kind: link
  value: ${application.namespace}

lifecycle:
  order:
  - s3-bucket
  - aws-iam
  - s3fuse

outputs:
- name: application.bucket.url
  value: ${application.bucket.endpoint}/minio/${application.bucket.name}
  brief: URL of a bucket that has been used to store application artifacts
