---
components:
- name: kaniko
  source:
    repoUrl: https://github.com/agilestacks/applications.git
    repoPath: applications/components/kaniko
    dir: components/kaniko
    branch: APPLICATIONS_TAG
    fromEnv: GITHUB_TOKEN

parameters:
- name: application.training.docker.registry.image
  kind: user
- name: application.jupyter.kernel.image
  kind: link
  value: ${application.training.docker.registry.image}:latest
- name: component.kaniko
  parameters:
  - name: name
    value: jupyter-kernel
  - name: namespace
    kind: link
    value: ${application.namespace}
  - name: destination
    kind: link
    value: ${application.training.docker.registry.image}:latest
  - name: contextDir
    value: components/kernel
  - name: build.timeout
    value: 1200
- name: component.kubeflow.url
- name: component.kubeflow.namespace

ouptuts:
- name: component.kaniko.build.timeout
  value: "${component.kaniko.build.timeout}"
- name: application.training.docker.registry.image
  value: "${application.training.docker.registry.image}"

lifecycle:
  order:
    - kaniko
