FROM python:3

WORKDIR /opt/webstream

RUN pip3 install flask numpy opencv-contrib-python imutils

COPY ./ ./
#COPY video video/
#COPY pyimagesearch pyimagesearch/
#COPY templates templates/
#COPY webstreaming.py ./

