.DEFAULT_GOAL := deploy

hub := hub

deploy:
	@echo "Deploy has been called"
	@echo "Workspace has been initialized: "
	@sleep 10
	@ls /workspace/repo	
.PHONY: deploy

undeploy:
	@echo "Undeploy has been called"
.PHONY: undeploy
